spring:
  application:
    name: hibernate-demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    dialect: org.hibernate.dialect.H2Dialect
    hikari:
      idleTimeout: 30000
      minimumIdle: 2
      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yml
    parameters:
      bigintColumnType: BIGINT
      uuidColumnType: UUID
      textColumnType: VARCHAR(255)
      descriptionColumnType: VARCHAR(MAX)
      booleanColumnType: BOOLEAN
      datetimeColumnType: TIMESTAMP WITH TIME ZONE
      doubleColumnType: DOUBLE
      intColumnType: INT
    contexts: h2
  h2:
    console:
      enabled: true
      path: /h2-console
